### ISSUE TITLE
The "shadow" setting makes no effect.

### ISSUE THREAD

**Issue by vrbvillor** [timdouglas/sublime-less2css#140]
```javascript
{
  "autoCompile": true,
  "createCssSourceMaps": false,
  "ignorePrefixedFiles": true,
  "lessBaseDir": "G:\\PHP\\WWW\\tea\\website\\less",
  "lesscCommand": false,
  "main_file": false,
  "minify": true,
  "minName": false,
  "outputDir": "shadow",
  "outputFile": "",
  "showErrorWithWindow": true,
  "autoprefix": false,
  "disableVerbose":false
}
```
Yesterday, I uninstall all of sublime, and reinstall them back.
Now new problem comes. I can't use the "shadow" to build one css folder which has the same subfolders as the less folder......
I use 'auto', the new css file will appear beside the less file.
Now I change it to 'shadow',  it won't compile at all.

**Comment by vrbvillor** [comment]
I remembered that before the reinstallation yesterday, I didn't use 'shadow' but 'auto'. It could make effect. When the less file is the child of the folder `less`, it should be compiled into `css` folder then be a child css file. When the less file is in a subfolder of `less`, the same subfolder would be build in to the `css` when compiling the less file, everything went as thought. 
But now, whether `shadow` or `auto` can't archeive the opition. `Auto` always does right when the less file is the child of folder `less`, but if the less file is in a subfolder, the css file will appear in the same subfolder in the `less` folder but not the `css`folder.
And `shadow` setting can't trigger the compile action at all, whatever I press CTRL+S or ALT+S, it's not compiled......

**Comment by vrbvillor** [comment]
It's exactly the new file's problem,  I roll back to 3 months ago, the "shadow" make effect.

**Comment by mattseymour** [comment]
Should now be fixed in master:11c0b116b6171ca83c69d6ef72a893b094d07a7d

**Comment by vrbvillor** [comment]
I use the sublime plugin,  it updates itself.   Today the files are updated at 8:56,   the problem comes out again......  When saving the new less file,   the cmd window  doesn't come out.

**Comment by vrbvillor** [comment]
And I paste the old files to the package directory,  the cmd shows when saving..

**Comment by mattseymour** [comment]
@vrbvillor please can you confirm what do you mean by: "When saving the new less file, the cmd window doesn't come out."

**Comment by vrbvillor** [comment]
@mattseymour  It means whether I press CTRL+S, or ALT+S, the "cmd" window doesn't come out. That means the compiling process fails. But I change the outputDir to 'auto' or paste the old Less2Css file to the package directory,  everything goes as normal.

**Comment by mattseymour** [comment]
@vrbvillor I have been able to confirm an issue with windows as I was unable to build given the settings you provided. Can you please give the following fix a test to see if it helps resolve your issue. It looks like there was an issue with a file path being generated.

Thanks

**Comment by vrbvillor** [comment]
Can you please give the following fix a test to see if it helps resolve your issue.

I'm not quite understand what you mean, please say more to describe this sentence.
BTW, the version which can achieve correctly is "df4044e", about 3 months ago.
I'm not exellent using git shell. I used the command 'git reset --hard df4044e' and got the old version.

**Comment by mattseymour** [comment]
A fix has been put into the main code base can you please update your plugin and it should be working now.

**Comment by vrbvillor** [comment]
Can you paste your settings on this page?    I uninstalled the less2css, and install again,  it still can't compile.......

**Comment by macias3** [comment]
I'm facing a similar issue. I'm using Windows and the path to less compiler is defined in PATH environment variable. Less files are being compiled correctly, but with "outputDir":"shadow" option they land in the wrong folder.

Actual result:
```
/app
  /css
  /less
    file.css  <- not expected
    file.less
```
Expected result:
```
/app
  /css
    file.css
  /less
    file.less
```
It worked as it should before updates in Dec 2015. Now I have to move newly created css files manually after compilation process finishes. Can you fix this, please? :)

**Comment by vrbvillor** [comment]
@macias3    df4044e    roll back to this version ,  I'm using it.

**Comment by macias3** [comment]
Thanks @vrbvillor, it seems to be the only solution for now. Version df4044e3c98f24cd41ba399125296836b11082f5  handles "shadow" option as expected. Looking forward to seeing a real fix soon :)

**Comment by mynameiskyle** [comment]
How do I rollback the sublime plugin to make the shadow work?

**Comment by macias3** [comment]
@mynameiskyle You can manually download this last working version - here's a direct link:
https://github.com/timdouglas/sublime-less2css/archive/df4044e3c98f24cd41ba399125296836b11082f5.zip.
Then replace all files in ```[Sublime Text path]/Data/Installed Packages/Less2Css.sublime-package``` package file. It's a zip archive, so you can open it in 7zip or similar software.
Perhaps there's simpler solution, but that worked for me.

**Comment by vrbvillor** [comment]
@mattseymour    Dear author,  is this problem fixed now?   You could see the comment above ,    they all use the older files......

**Comment by hozefaj** [comment]
I am also having the same issue, where `"outputDir": "shadow",` is not working. The complied CSS gets created in the same folder as the corresponding LESS file.
